---
swagger: "2.0"
info:
  description: "API to support the mobile application steps2save"
  version: "1.0.0"
  title: "Steps2Save Api"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /coupon:
    get:
      summary: "Get a coupon for a customer"
      operationId: "coupon_get"
      parameters:
      - name: "userId"
        in: "query"
        description: "Customer userId"
        required: true
        type: "string"
      responses:
        200:
          description: "New Coupon"
          schema:
            $ref: "#/definitions/Coupon"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /add:
    get:
      summary: "Adds an item to a user's shopping cart"
      operationId: "add_get"
      parameters:
      - name: "userId"
        in: "query"
        description: "Customer userId"
        required: true
        type: "string"
      - name: "productName"
        in: "query"
        description: "The name of the product"
        required: true
        type: "string"
      - name: "sku"
        in: "query"
        description: "SKU of product to be added"
        required: true
        type: "string"
      responses:
        200:
          description: "Item added successfully"
          schema:
            $ref: "#/definitions/Product"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /remove:
    get:
      summary: "Remove Item from a user's shopping cart"
      operationId: "remove_get"
      parameters:
      - name: "userId"
        in: "query"
        description: "Customer userId"
        required: true
        type: "string"
      - name: "productName"
        in: "query"
        description: "The name of the product"
        required: true
        type: "string"
      - name: "sku"
        in: "query"
        description: "SKU of product to be removed"
        required: true
        type: "string"
      responses:
        200:
          description: "Item removed succesfully"
          schema:
            $ref: "#/definitions/Product"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Coupon:
    type: "object"
    properties:
      title:
        type: "string"
      coupon_code:
        type: "string"
  Product:
    type: "object"
    properties:
      name:
        type: "string"
      sku:
        type: "string"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
      message:
        type: "string"
