---
swagger: "2.0"
info:
  description: "API to support the mobile applciation step2save"
  version: "1.0.0"
  title: "Step2Save Api"
host: "step2save.me"
basePath: "/v1"
schemes:
- "https"
produces:
- "application/json"
paths:
  /arrival:
    get:
      summary: "Check if device is located at a Wegman's store."
      description: ""
      operationId: "arrival_get"
      parameters:
      - name: "latitude"
        in: "query"
        description: "Latitude component of location."
        required: true
        type: "number"
        format: "double"
      - name: "longitude"
        in: "query"
        description: "Longitude component of location."
        required: true
        type: "number"
        format: "double"
      responses:
        200:
          description: "At Store"
          schema:
            type: "boolean"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /nearest:
    get:
      summary: "Find the nearest Wegman's Location"
      description: ""
      operationId: "nearest_get"
      parameters:
      - name: "latitude"
        in: "query"
        description: "Latitude component of location."
        required: true
        type: "number"
        format: "double"
      - name: "longitude"
        in: "query"
        description: "Longitude component of location."
        required: true
        type: "number"
        format: "double"
      responses:
        200:
          description: "The address of the nearest Wegman's."
          schema:
            $ref: "#/definitions/StreetAddress"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /search:
    get:
      summary: "Pass through for the Wegman's \"Products_SearchProducts\" endpoint"
      operationId: "search_get"
      parameters:
      - name: "criteria"
        in: "query"
        description: "The search criteria."
        required: true
        type: "string"
      responses:
        200:
          description: "The Wegman's search results."
          schema:
            $ref: "#/definitions/SearchResults"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /coupon:
    get:
      summary: "Get a coupon for a customer"
      operationId: "coupon_get"
      parameters:
      - name: "userId"
        in: "query"
        description: "Customer userId"
        required: true
        type: "string"
      responses:
        200:
          description: "The Wegman's search results."
          schema:
            $ref: "#/definitions/Coupon"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /add:
    get:
      summary: "Adds an item to a user's shopping cart"
      operationId: "add_get"
      parameters:
      - name: "userId"
        in: "query"
        description: "Customer userId"
        required: true
        type: "string"
      - name: "SKU"
        in: "query"
        description: "SKU of product to be added"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /remove:
    get:
      summary: "Remove Item from a user's shopping cart"
      operationId: "remove_get"
      parameters:
      - name: "userId"
        in: "query"
        description: "Customer UID"
        required: true
        type: "string"
      - name: "SKU"
        in: "query"
        description: "SKU of product to be removed"
        required: true
        type: "string"
      responses:
        200:
          description: "Item removed succesfully"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Coupon:
    type: "object"
    properties:
      name:
        type: "string"
      coupon_code:
        type: "string"
  StreetAddress:
    type: "object"
    properties:
      street_name:
        type: "string"
      city:
        type: "string"
      state:
        type: "string"
      zip:
        type: "integer"
  SearchResults:
    type: "object"
    properties:
      product_description:
        type: "string"
      product_sku:
        type: "integer"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
