# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Coupon(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, coupon_code: str=None):
        """
        Coupon - a model defined in Swagger

        :param name: The name of this Coupon.
        :type name: str
        :param coupon_code: The coupon_code of this Coupon.
        :type coupon_code: str
        """
        self.swagger_types = {
            'name': str,
            'coupon_code': str
        }

        self.attribute_map = {
            'name': 'name',
            'coupon_code': 'coupon_code'
        }

        self._name = name
        self._coupon_code = coupon_code

    @classmethod
    def from_dict(cls, dikt) -> 'Coupon':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coupon of this Coupon.
        :rtype: Coupon
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this Coupon.

        :return: The name of this Coupon.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Coupon.

        :param name: The name of this Coupon.
        :type name: str
        """

        self._name = name

    @property
    def coupon_code(self) -> str:
        """
        Gets the coupon_code of this Coupon.

        :return: The coupon_code of this Coupon.
        :rtype: str
        """
        return self._coupon_code

    @coupon_code.setter
    def coupon_code(self, coupon_code: str):
        """
        Sets the coupon_code of this Coupon.

        :param coupon_code: The coupon_code of this Coupon.
        :type coupon_code: str
        """

        self._coupon_code = coupon_code

