# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Steps2Save' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Steps2Save
	pod 'BarcodeScanner'
	pod 'PMAlertController'
	pod 'Haneke', '~> 1.0.2'
	pod 'SwiftSpinner'
	pod 'SwiftyJSON'
	pod 'Alamofire', '~> 4.5'
end
